In [1]:
import numpy as np
from IPython.display import Image

# Exercício 1
 Considere o exemplo visto em sala que usava uma Cadeia de Markov para ilustrar a transição de estados
para um indivíduo que possui o vírus do HIV. Se a população está distribu´ıda hoje conforme o vetor π =
(0.85, 0.10, 0.05, 0.00), qual ser´a a distribuição após 10 anos?

In [2]:
distribution = np.array([
                      [0.90, 0.07, 0.02, 0.01], 
                      [0.00, 0.93, 0.05, 0.02],
                      [0.00, 0.00, 0.85, 0.15],
                      [0.00, 0.00, 0.00, 1.00]
])
pi = np.array([0.85, 0.10, 0.05, 0.00])
for i in range(10):
    pi = pi@distribution

print("Answer = " + str(pi))


Answer = [0.29637667 0.3167509  0.1342175  0.25265492]


# Exercício 2
Considere o seguinte computador hipotético, onde a representação de um número em ponto flutuante em base 2 (binária) possui apenas 5 dígitos para a mantissa e o expoente pode variar entre -6 e 7. Tendo como
referência os padrões da IEEE apresentados em sala.

(a) Qual o menor número positivo que pode ser representado de forma exata?

>sign = 0 (positive),
mantissa = lowest possible (1.00000 = 1),
exponent = lowest possible (-6)

In [3]:
mantissa = 1
exponent = -6
base = 2
sign = 0
print("Answer = " + str(base**exponent*mantissa) + " or " + "(-1)^" + str(sign) + " . " + str(base) + "^(" + str(exponent) + ") . " + str(mantissa))

Answer = 0.015625 or (-1)^0 . 2^(-6) . 1


(b) Qual o maior?

>sign = 0 (positive), mantissa = max possible (1.11111 = 1.96875), exponent = max possible (7)
>
>1.11111 = (1 × 2⁰) + (1 × 2⁻¹) + (1 × 2⁻²) + (1 × 2⁻³) + (1 × 2⁻⁴) + (1 × 2⁻⁵) = 1.96875

In [4]:
mantissa = 1.96875
exponent = 7
base = 2
sign = 0
print("Answer = " + str(base**exponent*mantissa) + " or " + "(-1)^" + str(sign) + " . " + str(base) + "^(" + str(exponent) + ") . " + str(mantissa))

Answer = 252.0 or (-1)^0 . 2^(7) . 1.96875


(c) Como seria representado o número 2³ · (0.01010)base(2) neste computador?

>Para descobrirmos, basta andarmos com o ponto da mantissa e diminuímos o expoente em 1 a cada casa andada. E, como se trata de um número positivo, ficamos com o sinal = 0
>
>sinal = 0 (positive), mantissa = 1.01000 (1.25), exponent = 1
>
>1.01000 = (1 × 2⁰) + (0 × 2⁻¹) + (1 × 2⁻²) + (0 × 2⁻³) + (0 × 2⁻⁴) + (0 × 2⁻⁵) = 1.25
>
>Answer = (-1)⁰ . 2¹ . (1.01000)base(2)

(d) Como seria representado o número −2⁻² · (1101.01010)base(2) neste computador?

> Analogamente à questão acima, andamos com o ponto da mantissa, agora, para o lado contrário e aumentos um expoente.E, como só temos 5 dígitos para mantissa, mantemos os 5 mais significativos
>
>Sign = 1 (negative), mantissa = 1.10101, exponent = 1
>
>
>Answer = (-1)¹ . 2¹ . (1.10101)base(2)

(e) Qual é o menor número maior que 1 neste computador?

> 1 + menor numero possível que esse computador suporta
>
> 1.00001 = (1 × 2⁰) + (0 × 2⁻¹) + (0 × 2⁻²) + (0 × 2⁻³) + (0 × 2⁻⁴) + (1 × 2⁻⁵) = 1.03125
>
> signal = 0 (positive), mantissa = 1.00001 (= 1.03125), exponent = 0

In [5]:
mantissa = 1.03125
exponent = 0
base = 2
sign = 0
print("Answer = " + str(base**exponent*mantissa) + " or " + "(-1)^" + str(sign) + " . " + str(base) + "^(" + str(exponent) + ") . " + str(mantissa))

Answer = 1.03125 or (-1)^0 . 2^(0) . 1.03125


(f) Qual é o E machine?

> Machine Epsilon is half the distance between 1 and the next larger number.
>
> De acordo com a última questão, o menor número maior que 1 é 1.03125

In [6]:
print(str((1.03125-1)/2) + " == 2^(-6)")

0.015625 == 2^(-6)


# Exercício 3
![](questao-3.png)

![](questao-3-answer.jpeg)

# Exercício 4
![](questao-4.png)

> Deve-se checar que U e V são matrizes ortonormais (A é ortonormal se A(A^T) == (A^T)A == I). 
>
>Além disso, UE(V^T) == C

In [7]:
C = np.array([[1,-1], [0,1], [1,0], [-1, 1]])
U = np.array([[-0.632, 0.000], [0.316, -0.707], [-0.316, -0.707], [0.632, 0.000]])
UT = U.transpose()
E = np.array([[2.236, 0], [0.000, 1.000]])
VT = np.array([[-0.707, 0.707], [-0.707, -0.707]])
V = VT.transpose()

print("V is orthonormal:\n")
print(np.around(V@VT))
print(np.around(VT@V))

print("\nU is semi-orthonormal:\n")
print(np.around(U@UT))
print(np.around(UT@U))

print("\n\nUEVT == C:\n")
print(np.around(U@E@VT))

V is orthonormal:

[[1. 0.]
 [0. 1.]]
[[ 1. -0.]
 [-0.  1.]]

U is semi-orthonormal:

[[ 0. -0.  0. -0.]
 [-0.  1.  0.  0.]
 [ 0.  0.  1. -0.]
 [-0.  0. -0.  0.]]
[[ 1. -0.]
 [-0.  1.]]


UEVT == C:

[[ 1. -1.]
 [ 0.  1.]
 [ 1.  0.]
 [-1.  1.]]


# Exercício 5
![](questao-5.png)

> We need to add a value [a, b] to the end of U that [a,b].E.VT=[1,1]
>
> Since E@VT = [ [-1.580852, 1.580852], [-0.707, -0.707] ], we need to find a and b that when multiplied to E@VT, we get [1, 1], so, in this way, we will only add a [1, 1] at the end of C. Not changing it's properties
>
> Then we get -1.580852*a + -0.707*b = 1
> and 1.580852*a + -0.707*b = 1
>
> So, we get -1.414*b = 2
>
> and -3.161704*a = 0
>
> So we have: a = 0
> and b = -1,414427157
>
> And we checked it, adding [a, b] to U and calculating (U@E@VT)

In [8]:
a = 0
b = -1.414427157
C = np.array([[1,-1], [0,1], [1,0], [-1, 1]])
U = np.array([[-0.632, 0.000], [0.316, -0.707], [-0.316, -0.707], [0.632, 0.000], [0, b]])
E = np.array([[2.236, 0], [0.000, 1.000]])
VT = np.array([[-0.707, 0.707], [-0.707, -0.707]])

aux = E@VT
print([a, b]@aux)
print(np.around(U@E@VT))


[1. 1.]
[[ 1. -1.]
 [ 0.  1.]
 [ 1.  0.]
 [-1.  1.]
 [ 1.  1.]]
