In [2]:
import numpy as np

# Exercício 1

(a) Calcule a decomposição (manualmente) P A = LU Não precisa resolver Ly = P b, nem Ux = y.

In [3]:
A = np.array([[3, 2, 4], [1, 1, 2], [4, 3, -2]], dtype=float)
U = A.copy()
L = np.eye(3)
P = np.eye(3)
L[1][0] = A[1][0]/U[0][0]
U[1] = U[1] - U[0]/3

L[2][0] = A[2][0]/U[0][0]
U[2] = U[2] - U[0]*4/3

L[2][1] = U[1][1]/U[2][1]
U[2] = np.around(U[2]-U[1])

P@A == np.around(L@U)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

(b) Calcule o determinante de A a partir de P, L e U.

> Como det(A.P) = det(A).det(P) e det(P) = 1 (identidade), det(A.P) = det(A)
>
> Sendo assim, procuramos det(L.U) = det(L).det(U). Como L e U são matrizes triangulares, os seus determinantes = produto de suas matrizes diagonais.
>
> Como matriz diagonal de L = [1, 1, 1], det(L) = 1
>
> Já U, temos 3 . 1/3 . -8 = -8.
>
> det(A) = 1 . -8 = -8
>
> Isso pode ser observado abaixo:

In [3]:
round(np.linalg.det(A))

-8.0

# Exercício 2

Considere o sistema linear Ax = b, onde a matriz A = [[9 18],[18 52]] é simétrica e definida positiva. Sendo b = [3 4], encontre a solução usando a Decomposição de Cholesky.

In [4]:
import math 

L = np.zeros([2,2])
LT = np.zeros([2,2])

A = np.array([[9,18],[18,52]])
b = np.array([3,4])

#  9  18  * x = 3
#  18 52        4

L[0][0] = 3
LT[0][0] = 3
L[1][1] = 4
LT[1][1] = 4
L[1][0] = A[1][0]/L[0][0]
LT[0][1] = A[0][1]/L[0][0]


x = np.zeros(2)
# 9 18  = 3 
# 0 16  = -2
# x[1] = -2/16
# 9*x[0] + 18*(-1/8) = 3
# x[0] = (3-(-18/8))/9
x[1] = -2/16
x[0] = (3-(-18/8))/9

x, A@x

(array([ 0.58333333, -0.125     ]), array([3., 4.]))

# Exercício 3

(a) Para b = [3 4], calcule o erro residual (r = b − Ax) da solução aproximada dada por x⁽⁰⁾ = [0, 5 −0, 1]

In [7]:
A = np.array([[9,18],[18,52]])
b = np.array([3,4])
x0 = [0.5, -0.1]
r0 = b - A@x0
r0

array([0.3, 0.2])

(b) Use r para executar um refinamento da solução x (0)

In [17]:
# A@c0 = r0
c0 = np.linalg.solve(A, r0)
print("c0: \n", c0)
x1 = x0 + c0
A@x1

c0: 
 [ 0.08333333 -0.025     ]


array([3., 4.])

# Exercício 4 

 Assinale V para verdadeiro ou F para falso e justifique:

>( F )  A decomposição de Cholesky pode ser aplicada a qualquer matriz AtA tal que as entradas de A são números reais.
>
>    A decomposição de Cholesky só pode ser aplicada para matrizes simétrias e definidas positivas.
>
>( F )  Se C for uma matriz de permutação, então det(C A) = det(A)
>
>    Única coisa que podemos afirmar é que o |det(C A)| = |det(A)|, pois quando trocamos uma linha de uma matriz de permutação, invertemos o sinal do determinante.
>
>( F ) A fatoração LU é aproximadamente duas vezes mais demorada que a fatoração Cholesky, mas ambas requerem o mesmo espaço em memória.
>
>    De acordo com esse artigo: [https://www.researchgate.net/publication/316222249_Comparativo_entre_os_
Metodos_Numericos_Exatos_Fatoracao_LU_Doolittle_e_Fatoracao_de_Choleskys](https://www.researchgate.net/publication/316222249_Comparativo_entre_os_Metodos_Numericos_Exatos_Fatoracao_LU_Doolittle_e_Fatoracao_de_Choleskys) , a fatoração de Cholesky se apresenta em torno de 60% mais eficiente que a fatoração LU