In [1]:
import numpy as np

# Exercício 1

(a) Sem resolver o sistema, determine se este possui uma única solução.

> Sim. Esse sistema possui solução pois possui um pivô em cada linha

(b) Resolva utilizando o método das substituições sucessivas. (ONDE . = * ou "vezes")

> 4.x1 = 12, -2.x1 + 5.x2 = 4, 1.x1 + 7,x2 + 3.x3 = 20
>
> x1 = 3 , -2.3 + 5.x2 = 4, 1.3 + 7.x2 + 3.x3 = 20
>
> x1 = 3 , x2 = 2 , 3 + 7.2 + 3.x3 = 20
>
> x1 = 3 , x2 = 2 , x3 = 1
>
>[3, 2, 1]

# Exercício 2

Modifique o método LU (sem pivotação) abaixo para que funcione in-place. Isto é, a implementação não deve alocar memória nova para L ou U, mas sim sobrescrever A.

In [2]:
import pprint
import scipy.linalg

A = np.array([[3,2,4],[1,1,2],[4,3,-2]],dtype=float)

def LU(A):
    m, n = A.shape
    for k in range(n - 1):
        for j in range(k+1, n):
            m         = A[j,k] / A[k,k]
            A[j,k:n] -= m * A[k,k:n]
            A[j,k]    = m
    return A

L = LU(A)

print("A:")
pprint.pprint(A)

print("L:")
pprint.pprint(L)

A:
array([[ 3.        ,  2.        ,  4.        ],
       [ 0.33333333,  0.33333333,  0.66666667],
       [ 1.33333333,  1.        , -8.        ]])
L:
array([[ 3.        ,  2.        ,  4.        ],
       [ 0.33333333,  0.33333333,  0.66666667],
       [ 1.33333333,  1.        , -8.        ]])


# Exercício 3

(a) Calcule a decomposição A = LU. Não precisa resolver Ly = b, nem Ux = y.

In [3]:
from scipy.linalg import solve_triangular

A = np.array([[3,2,4],[1,1,2],[4,3,-2]], dtype=float)

B = LU(A)
L = np.eye(3)
U = np.zeros((3,3))
for i in range(3):
    for j in range(3):
        if (j >= i):
            U[i][j] = B[i][j]
        else:
            L[i][j] = B[i][j]
print("L \n", L, "\nU \n", U)

L 
 [[1.         0.         0.        ]
 [0.33333333 1.         0.        ]
 [1.33333333 1.         1.        ]] 
U 
 [[ 3.          2.          4.        ]
 [ 0.          0.33333333  0.66666667]
 [ 0.          0.         -8.        ]]


(b) Calcule o determinante da matriz A acima.

In [4]:
A = np.array([[3,2,4],[1,1,2],[4,3,-2]], dtype=float)

det = np.linalg.det(A)
int(round(det))

-8

# Exercício 4 

 Sejam o sistema linear Ax = b, de ordem n, e a matriz C de ordem n e não singular. Assinale V antes da sentença se ela for verdadeira e F se for falsa e justifique:

>( V ) A matriz CA não é singular.
>
>    Como o determinante do produto de duas matrizes é igual ao
> produto de seus determinantes, e nem C, nem A tem determinante 0,
> o determinante de CA != 0 e, por isso, CA não é singular.
>
>( F )  Se C for uma matriz de permutação, então det(C A) = det(A)
>
>    Como o determinante de toda matriz de permutação = + ou - 1,
> e o determinante do produto de duas matrizes é igual ao produto
> de seus determinantes, det(CA) pode ser igual det(A) ou -det(A)
>
>( V ) O sistema Ax = b não é necessariamente equivalente ao sistema C Ax = Cb.
>
>    Podemos ter b tal que Ax seja = b e Cb não necessariamente seja = Ax