In [1]:
import numpy as np
from sklearn.decomposition import TruncatedSVD
from IPython.display import Image

# Exercício 1

>
> Para que uma matriz possua posto 1, ela deve possuir apenas um pivo. Para isso, se todas as linhas forem múltiplas entre si, satisfazemos tal condição.
>
> Sendo assim, podemos partir do princípio que a última linha é a linha "indiminuível" e usar ela como referência. Como já temos 1 e 2 nela, conseguimos achar os valores da 1 e 2 coluna das linhas 1, 2 e 3:
>
> `a` = 6, `c` = 2, `e` = 6. Com isso, conseguimos descobrir `h` pela linha 3. `h` = 7
>
> E, com esses valores, conseguimos descobrir os valores restantes: `b` = 21, `d` = 14, `f` = 4 e `g` = 8
>
> Abaixo, testamos isso:

In [2]:
teste = np.array([[3, 'a', 'b'], ['c', 4, 'd'], ['e', 12, 42], ['f', 'g', 28], [1, 2, 'h']])
teste2 = np.array([[3, 6, 21], [2, 4, 14], [6, 12, 42], [4, 8, 28], [1, 2, 7]])

np.linalg.matrix_rank(teste2)

1

# Exercício 2


> Trocamos os `?` (arbitrariamente), respectivamente por 2, 3, 3, 4, pela média que foi passada

(a) Calcule B


In [3]:
A = np.array([
    [3, 4, 3, 1],
    [1, 2, 5, 3],
    [2, np.nan, np.nan, 4],
    [1, np.nan, np.nan, 1],
    [2, 4, 5, 3]
])

m = np.array([1.8, 3.0, 4.0, 2.4])
B = np.zeros((5, 4))

In [4]:
for i in range(5):
    for j in range(4):
        B[i][j] = A[i][j]-m[j]

B

array([[ 1.2,  1. , -1. , -1.4],
       [-0.8, -1. ,  1. ,  0.6],
       [ 0.2,  nan,  nan,  1.6],
       [-0.8,  nan,  nan, -1.4],
       [ 0.2,  1. ,  1. ,  0.6]])

(b) Calcule C

In [5]:
u = np.nanmean(B, axis=1)
C = np.zeros((5,4))

for i in range(5):
    for j in range(4):
        C[i][j] = B[i][j]-u[i]

C

array([[ 1.25,  1.05, -0.95, -1.35],
       [-0.75, -0.95,  1.05,  0.65],
       [-0.7 ,   nan,   nan,  0.7 ],
       [ 0.3 ,   nan,   nan, -0.3 ],
       [-0.5 ,  0.3 ,  0.3 , -0.1 ]])

(c) Sabendo que o SVD truncado de C truncado com k = 2 é ... determine uma aproximação (previsão) para as notas que os usuários 2 e 3 dariam as filmes 1 e 2 (assuma que os índices começam de 0).

In [6]:
U = np.array([
    [-0.62, -0.42],
    [0.47, 0.22],
    [0.5, -0.6],
    [-0.38, 0.19],
    [0.03, 0.61]])
s = np.array([[3.63, 0], [0, 1.05]])
VT = np.array([[-0.38, -0.61, 0.48, 0.51], [-0.75, 0.59, 0.28, -0.11]])

np.set_printoptions(precision=3)
resp = U@s@VT

for i in range(5):
    for j in range(4):
        resp[i][j] = resp[i][j]+u[i]+m[j]

np.round(resp)

array([[3., 4., 3., 1.],
       [1., 2., 5., 3.],
       [2., 2., 6., 4.],
       [1., 3., 2., 1.],
       [2., 4., 5., 3.]])

# Exercício 3
Assinale V ou F e justifique:

( F ) Em alguns casos é possível usar o NMF para reconstruir de maneira exata uma matriz A ∈ R
m×n mesmo que alguns elementos de A sejam negativos.

> NMF (Non-negative Matrix Factorization) é uma forma de decompor matrizes desde que essas matrizes contenham apenas elementos positivos. (ou melhor, elementos muito próximos de zero). De qualquer forma, essa afirmação é falsa pois não é possível reconstruí-la de maneira exata caso haja numeros negativos. Apenas aproximada.

( V ) Considere uma matriz A em que pode se aplicar tanto SVD quanto NMF. O erro (Frobenius) da
aproximação de posto k obtida pelo SVD será menor ou igual que o da aproximação de posto k obtida pelo
NMF.

> Como SVD é a melhor forma de decompor uma matriz, ela é a forma em que o erro da o menor possível. Sendo assim, a aproximação de NMF nunca será melhor do que a de um SVD, será sempre menor, ou no máximo, igual ao SVD.

# Exercício 4

In [7]:
A = np.array([
    [3, 0, 2],
    [9, 1, 7],
    [1, 0, 1]
])

(a) Norma-1

In [8]:
colSum = np.sum(A, axis=0)
np.amax(colSum)

13

(b) Norma-infinito

In [9]:
rowSum = np.sum(A, axis=1)
np.amax(rowSum)

17

(c) Norma-2 (Para este item você pode usar o numpy)

In [10]:
np.linalg.norm(A, 2)

12.074814532664146

(d) Norma Frobenius

In [11]:
np.linalg.norm(A, 'fro')

12.083045973594572

# Exercício 5
Considere o uso do SVD truncado de posto k para compressão de imagens em escala de cinza (0 a 255) de
tamanho 1024 x 768.

(a) No caso de uma única imagem decomposta usando SVD, quantos bytes precisam ser armazenados para
reconstruir a imagem, em função de k? Qual o valor máximo de k para o qual a compressão vale a
pena?

> Decompondo esssa imagem em SVD truncado, temos: U[1024][k] * E[k][k] * Vt[k][768]
>
> Dessa forma, atribuimos 1024k valores + k (como é uma matriz diagonal, podemos armazenar só k valores) + 768k.
>
> Assim temos 1793k valores. E, para que essa compressão valha a pena, esse número deve ser menor qe 1024*768 = 786432
>
> Ou seja, k < 786432/1793 = 438.61..
>
> Logo, `k`max = 438

(b) Agora suponha que queiramos usar um único SVD para comprimir várias imagens. Para isso, iremos
representar as imagens como vetores de tamanho 786432 (= 1024×768). Quantos bytes serão necessários
para armazenar 10 imagens? E quanto a 1000 imagens?

> Decompondo 10 imagems em SVD truncado, temos: U[1024*768][k] * E[k][k] * Vt[k][10]
>
> Dessa forma, atribuimos 786432 valores + k (como é uma matriz diagonal, podemos armazenar só k valores) + 10.
>
> Assim temos `786443k bytes`.
>
> No caso de 1000 imagens, só aumentamos 990 (em Vt) e, assim, temos `787433k bytes`.